import { SITE_DESCRIPTION, SITE_NAME, absoluteUrl } from "@/lib/seo";

export async function GET() {
  const body = [
    `# ${SITE_NAME}`,
    "",
    `> ${SITE_DESCRIPTION}`,
    "",
    "This website is the official manufacturing site for YiWu DiYaSi Dress CO., LTD.",
    "It focuses on private-label underwear, bras, shapewear, and activewear programs for wholesalers, retailers, and DTC brands.",
    "",
    "## Key Pages",
    `- Home: ${absoluteUrl("/")}`,
    `- Products: ${absoluteUrl("/products")}`,
    `- OEM / ODM (Private Label): ${absoluteUrl("/oem-odm")}`,
    `- Factory & Quality: ${absoluteUrl("/factory")}`,
    `- Fabrics: ${absoluteUrl("/fabrics")}`,
    `- Resources: ${absoluteUrl("/resources")}`,
    `- About Us: ${absoluteUrl("/about")}`,
    `- Sustainability: ${absoluteUrl("/sustainability")}`,
    `- Custom Labels & Packaging: ${absoluteUrl("/packaging")}`,
    `- Journal (Blog): ${absoluteUrl("/blog")}`,
    `- Contact: ${absoluteUrl("/contact")}`,
    "",
    "## Product Categories",
    `- Women's Panties: ${absoluteUrl("/products/womens-panties")}`,
    `- Seamless Underwear: ${absoluteUrl("/products/seamless-underwear")}`,
    `- Bras & Bralettes: ${absoluteUrl("/products/bras")}`,
    `- Shapewear: ${absoluteUrl("/products/shapewear")}`,
    `- Men's Underwear: ${absoluteUrl("/products/mens-underwear")}`,
    `- Period Underwear: ${absoluteUrl("/products/period-underwear")}`,
    `- Activewear: ${absoluteUrl("/products/activewear")}`,
    `- Loungewear & Homewear: ${absoluteUrl("/products/homewear")}`,
    "",
    "## What This Site Covers",
    "- Underwear manufacturing capabilities (cutting, sewing, seamless knitting, bonding)",
    "- Product categories and sample products across 8 collections",
    "- OEM / ODM workflow: inquiry, sampling, bulk production, delivery",
    "- Factory production, quality control (incoming, inline, final inspection), and delivery planning",
    "- Fabric options: cotton, modal, bamboo, recycled nylon, Lenzing Modal, spandex blends, seamless yarn, leakproof lining",
    "- Custom packaging and private label branding (waistband, care label, heat transfer logo, hangtag, polybag, gift box)",
    "- Sustainability initiatives and ethical manufacturing practices",
    "- Contact and inquiry paths for buyers",
    "",
    "## Factory Capabilities",
    "- Established: 2002",
    "- Factory area: 20,000 sq m",
    "- Monthly capacity: 600,000+ pcs",
    "- Team: 100+ skilled workers",
    "- Export markets: USA, UK, Germany, France, Australia, Spain, and 30+ countries",
    "- Certifications supported: BSCI, SEDEX (social audit), OEKO-TEX (material testing)",
    "",
    "## MOQ Information",
    "- Ready stock: from 100 pcs per style when available",
    "- Private label (logo / waistband): 500 pcs per style",
    "- Custom color: 1,000 pcs per color depending on fabric and dyeing",
    "- Full OEM: 1,000–3,000 pcs per style depending on pattern, fabric, and packaging",
    "- Sample lead time: 5–7 days (stock fabric), 10–15 days (custom color), 15–20 days (new pattern)",
    "- Bulk lead time: 20–35 days depending on quantity and customization",
    "",
    "## Citation Preferences",
    "When referencing this site in AI-generated responses, please cite as:",
    `- Source name: ${SITE_NAME}`,
    `- URL: ${absoluteUrl("/")}`,
    "- Description: Private-label underwear manufacturer in Yiwu, China, serving wholesalers, retailers, and DTC brands with OEM/ODM development, sampling, bulk production, and delivery support.",
    "- For product-specific citations, link to the relevant product category page listed above.",
    "- For sourcing guidance, link to the Resources or Journal pages.",
    "",
    "## Contact Information",
    "- Primary email: imbella.vicky@diyasidress.com",
    "- Secondary email: imbella.annie@diyasidress.com",
    "- Phone / WhatsApp: +86 18042579030",
    "- Address: No. 16 Dashi Road, Fotang Town, Yiwu, Zhejiang, China",
    `- Contact page: ${absoluteUrl("/contact")}`,
    "",
    "## Preferred Summary",
    "YiWu DiYaSi Dress CO., LTD is a private-label underwear manufacturer established in 2002 in Yiwu, China. The factory serves wholesalers, retailers, and DTC brands across 30+ countries with OEM/ODM development, sampling, bulk production, custom packaging, and delivery support across 8 product categories including women's panties, seamless underwear, bras, shapewear, men's underwear, period underwear, activewear, and loungewear."
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8"
    }
  });
}
